variable "name" {}
variable "zone" {}
variable "machine_type" {}
variable "image" {}
variable "ip_cidr_range" {}
variable "ports" {}
variable "credentials" {}
variable "project" {}
variable "region" {}