name: examples

on:
  push:
    branches:
      - master
    paths:
      - examples/**

  pull_request:
    paths:
      - examples/**

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
                
      - uses: marceloprado/has-changed-path@v1
        id: changed-front
        with:
          paths: packages/front

      - name: Deploy front
        run: echo steps.changed-front.outputs