name: examples

on:
  push:
    branches:
      - master
    paths:
      - examples/**

  pull_request:
    paths:
      - examples/**

jobs:
  example:
    name: 'example'
    runs-on: ubuntu-latest
    steps:
         - uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - uses: marceloprado/has-changed-path@master
      id: changed-front
      with:
        paths: examples/**
    
    - name: Deploy front
      if: steps.changed-front.outputs.changed == 'true'
      run: echo steps.changed-front.outputs