name: examples

on:
  push:
    branches:
      - master
    paths:
      - examples/**

  pull_request:
    paths:
      - examples/**

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
                
      - name: Get Path update
        run: cat `echo $GITHUB_EVENT_PATH`