name: examples

on:
  push:
    branches:
      - master
    paths:
      - examples/**

  pull_request:
    paths:
      - examples/**

jobs:
  example:
    name: 'example'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100

    # - uses: marceloprado/has-changed-path@master
    #   id: testong
    #   with:
    #     paths: examples/testong
    
    # - name: Deploy front
    #   if: steps.testong.outputs.changed == 'true'
    #   run: echo "hellow"

    - name: check1
        id: filepath
        run: |
          echo ::set-output name=commitpath::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})

      - name: echo
        run: |
          echo ${{ steps.filepath.outputs.commitpath }}