name: examples

on:
  push:
    branches:
      - master
    paths:
      - examples/**

  pull_request:
    paths:
      - examples/**

jobs:
  example:
    name: 'example'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - name: get path
      id: testong
      run: echo ::set-output name=path::${{ hashFiles('**/testong/**') }}
    
    - name: Deploy front
      run: echo ${{ steps.testong.outputs.path }}